export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'af', name: 'Afrikaans', flag: 'za' },
  { code: 'sq', name: 'Albanian', flag: 'al' },
  { code: 'am', name: 'Amharic', flag: 'et' },
  { code: 'ar', name: 'Arabic', flag: 'sa' },
  { code: 'hy', name: 'Armenian', flag: 'am' },
  { code: 'az', name: 'Azerbaijani', flag: 'az' },
  { code: 'eu', name: 'Basque', flag: 'es' },
  { code: 'be', name: 'Belarusian', flag: 'by' },
  { code: 'bn', name: 'Bengali', flag: 'bd' },
  { code: 'bs', name: 'Bosnian', flag: 'ba' },
  { code: 'bg', name: 'Bulgarian', flag: 'bg' },
  { code: 'ca', name: 'Catalan', flag: 'es' },
  { code: 'ceb', name: 'Cebuano', flag: 'ph' },
  { code: 'ny', name: 'Chichewa', flag: 'mw' },
  { code: 'zh', name: '中文', flag: 'cn' },
  { code: 'co', name: 'Corsican', flag: 'fr' },
  { code: 'hr', name: 'Croatian', flag: 'hr' },
  { code: 'cs', name: 'Czech', flag: 'cz' },
  { code: 'da', name: 'Danish', flag: 'dk' },
  { code: 'nl', name: 'Dutch', flag: 'nl' },
  { code: 'en', name: 'English', flag: 'gb' },
  { code: 'eo', name: 'Esperanto', flag: 'eu' },
  { code: 'et', name: 'Estonian', flag: 'ee' },
  { code: 'tl', name: 'Filipino', flag: 'ph' },
  { code: 'fi', name: 'Finnish', flag: 'fi' },
  { code: 'fr', name: 'Français', flag: 'fr' },
  { code: 'fy', name: 'Frisian', flag: 'nl' },
  { code: 'gl', name: 'Galician', flag: 'es' },
  { code: 'ka', name: 'Georgian', flag: 'ge' },
  { code: 'de', name: 'Deutsch', flag: 'de' },
  { code: 'el', name: 'Greek', flag: 'gr' },
  { code: 'gu', name: 'Gujarati', flag: 'in' },
  { code: 'ht', name: 'Haitian Creole', flag: 'ht' },
  { code: 'ha', name: 'Hausa', flag: 'ng' },
  { code: 'haw', name: 'Hawaiian', flag: 'us' },
  { code: 'iw', name: 'Hebrew', flag: 'il' },
  { code: 'hi', name: 'Hindi', flag: 'in' },
  { code: 'hmn', name: 'Hmong', flag: 'cn' },
  { code: 'hu', name: 'Hungarian', flag: 'hu' },
  { code: 'is', name: 'Icelandic', flag: 'is' },
  { code: 'ig', name: 'Igbo', flag: 'ng' },
  { code: 'id', name: 'Indonesian', flag: 'id' },
  { code: 'ga', name: 'Irish', flag: 'ie' },
  { code: 'it', name: 'Italiano', flag: 'it' },
  { code: 'ja', name: '日本語', flag: 'jp' },
  { code: 'jw', name: 'Javanese', flag: 'id' },
  { code: 'kn', name: 'Kannada', flag: 'in' },
  { code: 'kk', name: 'Kazakh', flag: 'kz' },
  { code: 'km', name: 'Khmer', flag: 'kh' },
  { code: 'ko', name: '한국어', flag: 'kr' },
  { code: 'ku', name: 'Kurdish', flag: 'tr' },
  { code: 'ky', name: 'Kyrgyz', flag: 'kg' },
  { code: 'lo', name: 'Lao', flag: 'la' },
  { code: 'la', name: 'Latin', flag: 'va' },
  { code: 'lv', name: 'Latvian', flag: 'lv' },
  { code: 'lt', name: 'Lithuanian', flag: 'lt' },
  { code: 'lb', name: 'Luxembourgish', flag: 'lu' },
  { code: 'mk', name: 'Macedonian', flag: 'mk' },
  { code: 'mg', name: 'Malagasy', flag: 'mg' },
  { code: 'ms', name: 'Malay', flag: 'my' },
  { code: 'ml', name: 'Malayalam', flag: 'in' },
  { code: 'mt', name: 'Maltese', flag: 'mt' },
  { code: 'mi', name: 'Maori', flag: 'nz' },
  { code: 'mr', name: 'Marathi', flag: 'in' },
  { code: 'mn', name: 'Mongolian', flag: 'mn' },
  { code: 'my', name: 'Myanmar', flag: 'mm' },
  { code: 'ne', name: 'Nepali', flag: 'np' },
  { code: 'no', name: 'Norwegian', flag: 'no' },
  { code: 'ps', name: 'Pashto', flag: 'af' },
  { code: 'fa', name: 'Persian', flag: 'ir' },
  { code: 'pl', name: 'Polish', flag: 'pl' },
  { code: 'pt', name: 'Portuguese', flag: 'pt' },
  { code: 'pa', name: 'Punjabi', flag: 'in' },
  { code: 'ro', name: 'Romanian', flag: 'ro' },
  { code: 'ru', name: 'Русский', flag: 'ru' },
  { code: 'sm', name: 'Samoan', flag: 'ws' },
  { code: 'gd', name: 'Scots Gaelic', flag: 'gb' },
  { code: 'sr', name: 'Serbian', flag: 'rs' },
  { code: 'st', name: 'Sesotho', flag: 'ls' },
  { code: 'sn', name: 'Shona', flag: 'zw' },
  { code: 'sd', name: 'Sindhi', flag: 'pk' },
  { code: 'si', name: 'Sinhala', flag: 'lk' },
  { code: 'sk', name: 'Slovak', flag: 'sk' },
  { code: 'sl', name: 'Slovenian', flag: 'si' },
  { code: 'so', name: 'Somali', flag: 'so' },
  { code: 'es', name: 'Español', flag: 'es' },
  { code: 'su', name: 'Sundanese', flag: 'id' },
  { code: 'sw', name: 'Swahili', flag: 'tz' },
  { code: 'sv', name: 'Swedish', flag: 'se' },
  { code: 'tg', name: 'Tajik', flag: 'tj' },
  { code: 'ta', name: 'Tamil', flag: 'in' },
  { code: 'te', name: 'Telugu', flag: 'in' },
  { code: 'th', name: 'Thai', flag: 'th' },
  { code: 'tr', name: 'Turkish', flag: 'tr' },
  { code: 'uk', name: 'Ukrainian', flag: 'ua' },
  { code: 'ur', name: 'Urdu', flag: 'pk' },
  { code: 'uz', name: 'Uzbek', flag: 'uz' },
  { code: 'vi', name: 'Tiếng Việt', flag: 'vn' },
  { code: 'cy', name: 'Welsh', flag: 'gb' },
  { code: 'xh', name: 'Xhosa', flag: 'za' },
  { code: 'yi', name: 'Yiddish', flag: 'il' },
  { code: 'yo', name: 'Yoruba', flag: 'ng' },
  { code: 'zu', name: 'Zulu', flag: 'za' }
];